GPU available: True, used: False
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/trainer.py:1585: UserWarning: GPU available but not used. Set the gpus flag in your trainer `Trainer(gpus=1)` or script `--gpus=1`.
  "GPU available but not used. Set the gpus flag in your trainer `Trainer(gpus=1)` or script `--gpus=1`."
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
  0%|                                                                                                                        | 0/100 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "trainer.py", line 138, in <module>
    main()
  File "trainer.py", line 132, in main
    trainer.fit(landclassifier)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/trainer.py", line 741, in fit
    self._fit_impl, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/trainer.py", line 685, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/trainer.py", line 777, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/trainer.py", line 1131, in _run
    self._data_connector.prepare_data()
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/connectors/data_connector.py", line 168, in prepare_data
    self.trainer.call_hook("prepare_data")
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/trainer.py", line 1501, in call_hook
    output = model_fx(*args, **kwargs)
  File "trainer.py", line 61, in prepare_data
    test_size = self.test_size)
  File "/home/noah/nyc-sentinel/src/load_data.py", line 14, in get_eurosat_dataloaders
    image_df, label_dict = load_eurosat_dataset(limit=limit)
  File "/home/noah/nyc-sentinel/src/load_data.py", line 79, in load_eurosat_dataset
    paths.append(img)
NameError: name 'img' is not defined